# Suppression de la moyenne

In [5]:
import numpy as np
from sklearn import preprocessing

#Construire le tableau
data = np.array([[ 3, -1.5,  2, -5.4],
                 [ 0,  4,  -0.3, 2.1],
                 [ 1,  3.3, -1.9, -4.3]])

# mean removal
data_standardized = preprocessing.scale(data)
print(data_standardized)


[[ 1.33630621 -1.40451644  1.29110641 -0.86687558]
 [-1.06904497  0.84543708 -0.14577008  1.40111286]
 [-0.26726124  0.55907936 -1.14533633 -0.53423728]]


# Mise à l'echelle min-max

In [4]:
import numpy as np
from sklearn import preprocessing

#Construire le tableau
data = np.array([[ 3, -1.5,  2, -5.4],
                 [ 0,  4,  -0.3, 2.1],
                 [ 1,  3.3, -1.9, -4.3]])

# min max scaling sur un interval donné
data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 2))
data_scaled = data_scaler.fit_transform(data)
print(data_scaled)

[[ 2.          0.          2.          0.        ]
 [ 0.          2.          0.82051282  2.        ]
 [ 0.66666667  1.74545455  0.          0.29333333]]


# Binarisation

In [7]:
import numpy as np
from sklearn import preprocessing

#Construire le tableau
data = np.array([[ 3, -1.5,  2, -5.4],
                 [ 0,  4,  -0.3, 2.1],
                 [ 1,  3.3, -1.9, -4.3]])

# binarization
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print(data_binarized)

[[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  1.  0.  0.]]


# Encodage categoriel

In [8]:
import numpy as np
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
input_classes = ['subaru','audi', 'ford', 'audi', 'toyota', 'ford', 'bmw']#ordre alphabetique
label_encoder.fit(input_classes)
# transformer un ensemble de classes
labels = ['toyota', 'ford', 'audi','subaru']
encoded_labels = label_encoder.transform(labels)
print(encoded_labels)

[4 2 0 3]
